version: '3.1'
 
services:
   db:
     image: mysql
     restart: always
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: productdb
       MYSQL_USER: hilllab
       MYSQL_PASSWORD: hilllab
     volumes:
       - ./dbscript:/docker-entrypoint-initdb.d
    
   hilllabtestapp:
     depends_on:
       - db
     image: huangsoft/hill_lab_test:build
     build:
       context: .
     ports:
       - "8080:5000"
